### ISSUE TITLE
Changes not saving.

### ISSUE THREAD

**Issue by Boozekashi** [jneilliii/OctoPrint-DragonOrder#13]
MacOS Mojave latest version of DragonOrder + new Octoprint install.

Plugin installs normally, no issues.  Tabs & sidebar items can be rearranged. Popup message about Shift + Reload/Refresh when finished appears.

Pressing Shift+Refreshing the page reverts all changes to original settings, nothing is saved.

Command+Option+R (Mac keyboard shortcut for hard refresh) also yields the same result. Not saved, everything back to default.

*Edit*
Found that although the re-ordering would revert after a browser refresh, that if the OctoPrint instance itself was restarted, then the changes would appear in place when new instance loaded.

**Comment by jneilliii** [comment]
Can you check your config.yaml to see if the settings are getting updated? Any errors in the logs or developer console of the browser?

**Comment by jneilliii** [comment]
Just saw the edit to your post.  Are you using the latest 1.4.0 RC3?  I think this may be a change to that version that broke the default behavior.

**Comment by neutralscheme** [comment]
I am experiencing the same issue using commit 76ff54b426b42c1c85bb93edb345f1129bbabf86 from master. Where can I find the mentioned config.yaml to see if the settings are updated?

**Comment by jneilliii** [comment]
If on a pi you can run `nano ~/.octoprint/config.yaml`. But as OP mentioned it looks like a restart of octoprint itself might be necessary.

**Comment by codingcatgirl** [comment]
Please disable stalebot. I am having this issue too and it doesn't magically disappear just because people don't talk about it for 2 weeks. This issue is a prime example for why stalebot is bad.

**Comment by jneilliii** [comment]
> Please disable stalebot. I am having this issue too and it doesn't magically disappear just because people don't talk about it for 2 weeks. This issue is a prime example for why stalebot is bad.

I'd be happy to re-open, but when I don't get replies from people that reach out for help I don't want my tracker cluttered. Although you came here to also get help, you didn't provide any additional details as previously requested from the OP, and subsequent requests to others for the same info. If there's no response, I'm not going to waste my time. Can you please let me know after using dragon order to move stuff around if your config.yaml changes or not in the appearance section?

**Comment by Sebclem** [comment]
Hi! 

I have the same issue.

The settings is correctly  updating  when i move a tab: 
In `config.yaml` :
```yml
appearance:
    color: black
    colorIcon: false
    components:
        order:
            navbar:
            [...]
            sidebar:
            [...]
            tab:
            - plugin_dashboard
            - temperature
            - control
            - gcodeviewer
            - timelapse
            - terminal
            - plugin_continuousprint
            - plugin_resource_monitor
            - plugin_bedlevelvisualizer
```
But in the GUI:
![image](https://user-images.githubusercontent.com/23737709/89297784-baf65180-d664-11ea-9452-026a86192793.png)

 gcodeviewer is not in the right place.

So, i don't know if it's related to your plugin because the config seems good.
